[profile.default]
solc = "0.8.25"
src = "src"
out = "out"
libs = ["lib"]

optimizer = false
optimize-runs = 0
auto_detect_solc = true

show-progress = true


[invariant]
depth = 1000
shrink_run_limit = 999
runs = 10
fail_on_revert = true
show_metrics = true
timeout = 18000
